### ISSUE TITLE
Accepting options

### ISSUE THREAD

**Issue by kneeki** [HannahMitt/HomeMirror#29]
Hello, I'm new to the android development circle and I need a tip. I've got Android Studio working with an emulated device (Nexus 5, see screenshot). However, once I enter my options, I don't see how to accept the settings I've specified.

I'm very sorry for the obvious question. -.-
![capture](https://cloud.githubusercontent.com/assets/1012169/10325671/4dbd48fc-6c48-11e5-82d2-75500c0b5373.PNG)

**Comment by HannahMitt** [comment]
Hi @kneeki ! Yeah sorry about that. I'd only developed it against tablets, but I fixed it to work on phones last night. Try updating to the current head.

**Comment by kneeki** [comment]
Will do! Thank you!
On Wed, Oct 7, 2015 at 6:36 AM Hannah Mittelstaedt <notifications@github.com>
wrote:

> Hi @kneeki <https://github.com/kneeki> ! Yeah sorry about that. I'd only
> developed it against tablets, but I fixed it to work on phones last night.
> Try updating to the current head.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HannahMitt/HomeMirror/issues/29#issuecomment-146198236>
> .
>
-- 
Sent from my iPhone. Forgive the brevity, the typos and the lack of nuance.

**Comment by kneeki** [comment]
Thanks for the help @HannahMitt! It's working wonderfully. =)
