### ISSUE TITLE
[Suggestion] Wireless sync

### ISSUE THREAD

**Issue by magroski** [HannahMitt/HomeMirror#3]
From what I saw, you have to hard code your calendar, stocks, birthdays and such before compiling and deploying the code. It'd be cool if a future version provided wireless sync with another device. It'd probably need the coding of a second app to allow your mirror to mirror - pun intended - your main device.

**Comment by osidenate** [comment]
:+1:

**Comment by MartinIngesen** [comment]
Alternatively, the app could be a regular webview, showing a custom website for the mirror. This way one could update the webpage from anywhere, and the app would show the updated webpage.

**Comment by GabLeRoux** [comment]
Could be quickly done with [meteorjs](https://www.meteor.com). Push working code and connected client will refresh itself automagically :)

**Comment by mikeatlas** [comment]
Yeah :+1: for meteorjs @GabLeRoux, for personal 1-off projects it's a good choice for a simple text website that makes development (front/backend changes) super quick. Although hosting it somewhere is still a problem, the buildpack on heroku for it is mega slow to compile new deployed changes. And you'd have to probably pre-boot ping a free dyno to wake it up around the time of day you want to look at your mirror... rabbit hole.

**Comment by ivan-saorin** [comment]
Though one could buid a Cordova wrapper with its WebView pointing to a remote static web site. Being static it can be hosted on whatever you need / want. It will be easy to update and it can be done in whatever your preference are in terms of MVW (AngularJS, React, etc.). Also minifing (e.g. with Gulp) the app with gulp could drammatically reduce the number of files: usually one js and one css.

[Here](https://www.ibm.com/developerworks/mydeveloperworks/blogs/94e7fded-7162-445e-8ceb-97a2140866a9/entry/dynamic_page_loading_for_phonegap1?lang=en) an interesting article on how to load webviews in Cordova / PhoneGap.

**Comment by alexbate** [comment]
Alternatively, you could run a local Web server on the tablet and configure it from a html page on your phone/laptop

**Comment by alexbate** [comment]
I've created Pull Request #23 to allow for configuration from another device.

**Comment by HannahMitt** [comment]
I've made the app configurable in-app before launch. There's pros/cons to my method, but I thought it would make it simpler as a stand-alone Google Play store app.

Please feel free to maintain a branched wireless sync version, but I'm going to close this issue for now.
