### ISSUE TITLE
Come see me talk about the mirror at AndroidTO

### ISSUE THREAD

**Issue by HannahMitt** [HannahMitt/HomeMirror#35]
If you happen to be in Toronto, I'll be talking mirror stuff at AndroidTO on Dec 1.
http://androidto.com/

**Comment by samrocketman** [comment]
If there's a video of the presentation, then please post it.

**Comment by dtmonterrey** [comment]
@HannahMitt yes please, a video :)

**Comment by HannahMitt** [comment]
Unfortunately no video!
