### ISSUE TITLE
No R.string.dark_sky_api_key in your project.

### ISSUE THREAD

**Issue by LittlePanpc** [HannahMitt/HomeMirror#38]
I tried to download your project in **Intellij**. But it can't be compiled. It's showed int **Messages** console: 
`Error:(43, 81) Gradle: error: cannot find symbol variable dark_sky_api_key`

So could your update your project?

**Comment by HannahMitt** [comment]
Hi! So I don't actually include the DarkSky API key with the project since it is subject to rate limiting.

In the project instructions, it asks you to copy in your own.
You can register and create your own key here: https://developer.forecast.io/
