### ISSUE TITLE
F-droid

### ISSUE THREAD

**Issue by moshpirit** [HannahMitt/HomeMirror#40]
Hi! I love your app but it's not available on [F-droid](http://f-droid.org/), could you do share it there too, please? 

Thanks a lot for this amazing app!!

**Comment by HannahMitt** [comment]
Hi! I'm not a user of F-droid, but as far as I can tell, projects don't have to be submitted by the maintainer.
Feel free to submit!

**Comment by moshpirit** [comment]
[Done](https://f-droid.org/forums/topic/homemirror/), thanks! :D

**Comment by moshpirit** [comment]
OK, looks like [there's some troubles](https://f-droid.org/forums/topic/homemirror/#post-18558) :(

**Comment by HannahMitt** [comment]
@moshpirit Both Crashlytics and Play Services are free. The use of Crashlytics is only an option. It can be turned on for release builds.
However, the forecast.io API, which needs the API key, is not free.

Haven't looked into their rules. Seems a little odd.

**Comment by KeiroD** [comment]
@HannahMitt Forecast.io API gives you 1000 pulls a day. The API key is free. After you hit the 1000 checks cap, you need to pay.

See: https://developer.forecast.io/

**Comment by moshpirit** [comment]
When I see free I mean as in freedom (like *libre*).

OK, thank you so much for all your work anyway, Hanna :)

**Comment by KeiroD** [comment]
Personally, I'd love to have Forecast.io integration.

**Comment by HannahMitt** [comment]
@KeiroD this project does have forecast.io integration. It uses forecast.io for the displayed weather, and biking logic.
