### ISSUE TITLE
Full display mirror

### ISSUE THREAD

**Issue by mavencode01** [HannahMitt/HomeMirror#5]
Just wandering how to display more contents than a screen size tablet will take
on the mirror?

Probably use multiple tablets to display the more contents ?

**Comment by icebob** [comment]
Or you use an LCD monitor with Rpi as Michael Teeuw: http://michaelteeuw.nl/tagged/magicmirror

**Comment by HannahMitt** [comment]
Bigger display definitely works!
Feel free to add to this wiki of alternative projects and solutions
https://github.com/HannahMitt/HomeMirror/wiki/Other-mirror-projects-with-alternate-technologies
