### ISSUE TITLE
Crashlytics Developer Tools error.

### ISSUE THREAD

**Issue by joeDiHare** [HannahMitt/HomeMirror#50]
Hi Hanna, nice work.

I get the following error (I am using Google studio):

> Error:Execution failed for task ':app:fabricGenerateResourcesRelease'.
> > Crashlytics Developer Tools error.

Is there a way to disable Crashlytics?

**Comment by HannahMitt** [comment]
@joeDiHare Crashlytics should be disabled when running the Debug rather than the Release flavor. Let me know if that doesn't help!

**Comment by sriramji** [comment]
@HannahMitt why should disable crashlytics for debug build?
I want crashlytics for debug build also
