### ISSUE TITLE
Starting the app

### ISSUE THREAD

**Issue by honza** [HannahMitt/HomeMirror#6]
How do you start the app if the tablet dies? Maybe set it as the home activity so it starts on boot?

**Comment by Fleker** [comment]
You might be able to use Tasker to do that.

**Comment by HannahMitt** [comment]
My tablet has been trucking really well, and actually hasn't shut down in weeks.

But I will look into it. There are definitely ways to get it to launch on boot.

**Comment by git-commit** [comment]
You could make sure you have adb turned on and a device trusted. You can use an adb connected computer to run the app with this command:

`adb shell am start  -n "com.morristaedt.mirror/com.morristaedt.mirror.MirrorActivity"`

**Comment by HannahMitt** [comment]
I've decided not to make it an app that forces mirror mode on boot, in case the device is only being used as a mirror part-time.
