### ISSUE TITLE
Question: what are the dimensions of the mirror in your example?

### ISSUE THREAD

**Issue by lambtron** [HannahMitt/HomeMirror#7]
Thanks!!

**Comment by ajvb** [comment]
@HannahMitt Seconded. Also, could you please provide more details on how to buy that kind of mirror?

**Comment by plondon** [comment]
@ajvb She links to here: http://canalplastic.com/. I just bought one for 42x28 inches for $200. Super helpful and quick service. They also deliver if you're not in NYC.

**Comment by HannahMitt** [comment]
Mine is 6'x12'
Thickness: 1/16

I'll add to the README
